# Overview
# * postgres target
# * fal target

# Resources
# * https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml
# * https://docs.getdbt.com/docs/core/connect-data-platform/fal-setup

# config
config:
  fail_fast: true

# targets
ffd:
  
  # default target
  target: public
  
  # outputs = targets
  outputs:

    # public
    public:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"

    # fal
    fal:
      type: fal
      db_profile: public