# https://docs.getdbt.com/docs/core/connect-data-platform/profiles.yml
config:
  fail_fast: true

ffd:
  
  # default target
  target: public
  
  # outputs = targets
  outputs:

    # staging
    public:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"