name: ffd

config-version: 2
version: 1.0.0

profile: ffd

seeds:
  ffd:
    +enabled: true
    +schema: a_seeds

# https://docs.getdbt.com/reference/model-configs
models:
  # Be sure to namespace your model configs to your project name
  ffd:

    # staging
    b_stg:
      +enable: true
      +schema: b_stg
      +materialized: table

    # intermedate
    c_int:
      +enable: true
      +schema: c_int
      +materialized: table

    # mart
    d_mrt:
      +enable: true
      +schema: d_mrt
      +materialized: table